# Generated by Django 5.2.9 on 2026-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('resume', 'Resume Writing'), ('career', 'Career Support'), ('academic', 'Academic Help'), ('other', 'Other')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
