# Generated by Django 5.2.9 on 2026-01-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studos', '0002_assistancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='service',
            field=models.CharField(choices=[('resume', 'Resume Writing'), ('career', 'Career Support'), ('academic', 'Academic Help'), ('digital', 'Digital Support'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
