# Generated by Django 5.2.9 on 2026-01-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studos', '0003_assistancerequest_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='service',
            field=models.CharField(choices=[('resume', 'Resume Writing'), ('career', 'Career Support'), ('academic', 'Academic Help'), ('skill', 'Skill Support'), ('digital', 'Digital Support'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
